### ISSUE TITLE
Output fetch does not wait for command to complete

### ISSUE THREAD

**Issue by itssuyog96** [ankschoubey/Hadoop-Mini-Project#4]
In the following lines of **hadoop.py** 
```
command = """{hadoop_path} jar {streaming_path} \
         -mapper {mapper_arguments}    -file {mapper}  \
         -reducer {reducer_arguments}    -file {reducer}  \
        -input {input}  -output {output} """.format(hadoop_path=hadoop_path,mapper=mapper, mapper_arguments = mapper_arguments, reducer_arguments = reducer_arguments, reducer=reducer, input=input_path, output=output, streaming_path=streaming_path)

os.popen(command)

return output_fetch(output, hadoop_path=hadoop_path)
```

the `output_fetch` function gets executed before the completion of `os.popen(command)`. This causes reading of _non existing_ output folder.

**Comment by itssuyog96** [comment]
This issue is specific to python 3

**Comment by ankschoubey** [comment]
Fixed! 

Hadoop class has a new ```shell()``` function which uses ```subprocess``` for execution instead of ```os``` and it will wait for the entire execution to complete.
